<a href="https://colab.research.google.com/github/karanamsubbarao/Python-Exercises/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#Numpy is used for Numerical Computing and is foundational for understanding Tensors
import numpy as np

print("Numpy imported successfully")

# 1D Array
numbers = np.array([1,2,3,4])
print("1-Dimensional Array" ,numbers)
print(type(numbers))
print("1-Dimensional Array Shape" ,numbers.shape)

#2D Array
darray = np.array([
    [1,2,3,4],
    [5,6,7,8]]);
print("2-Dimensional Array",darray)
print(type(numbers))
print("2-Dimensional Array Shape" ,darray.shape)



Numpy imported successfully
1-Dimensional Array [1 2 3 4]
<class 'numpy.ndarray'>
1-Dimensional Array Shape (4,)
2-Dimensional Array [[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2-Dimensional Array Shape (2, 4)


In [17]:
## Creating Special Arrays
zeros = np.zeros((3,4))
print(zeros)

ones = np.ones((2,5))
print(ones)

random_array = np.random.rand(3,3)
print("Random Values between 0 and 1")
print(random_array)

random_normal = np.random.randn(3,3)
print("Random Values from Normal Distribution")
print(random_normal)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Random Values between 0 and 1
[[0.53540156 0.83754366 0.53221386]
 [0.47800462 0.90325525 0.46851501]
 [0.22455981 0.0742872  0.98944124]]
Random Values from Normal Distribution
[[ 0.66880286 -1.14530728 -0.6132102 ]
 [ 0.48512882 -0.77634417  2.47846377]
 [-1.22804984 -1.44750407  0.06115387]]


In [22]:
#### Indexing Numpy Arrays ####

x = np.array([10,20,30,40,50])
print("Array:" , x)
print("Length of Array:" , len(x))

print("First Element", x[0])
print("Last Element", x[-1])
print("First 3 Elements", x[:3])
print("Last 3 Elements", x[2:])


Array: [10 20 30 40 50]
Length of Array: 5
First Element 10
Last Element 50
First 3 Elements [10 20 30]
Last 3 Elements [30 40 50]
