<a href="https://colab.research.google.com/github/karanamsubbarao/Python-Exercises/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#Numpy is used for Numerical Computing and is foundational for understanding Tensors
import numpy as np

print("Numpy imported successfully")

# 1D Array
numbers = np.array([1,2,3,4])
print("1-Dimensional Array" ,numbers)
print(type(numbers))
print("1-Dimensional Array Shape" ,numbers.shape)

#2D Array
darray = np.array([
    [1,2,3,4],
    [5,6,7,8]]);
print("2-Dimensional Array",darray)
print(type(numbers))
print("2-Dimensional Array Shape" ,darray.shape)



Numpy imported successfully
1-Dimensional Array [1 2 3 4]
<class 'numpy.ndarray'>
1-Dimensional Array Shape (4,)
2-Dimensional Array [[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2-Dimensional Array Shape (2, 4)


In [17]:
## Creating Special Arrays
zeros = np.zeros((3,4))
print(zeros)

ones = np.ones((2,5))
print(ones)

random_array = np.random.rand(3,3)
print("Random Values between 0 and 1")
print(random_array)

random_normal = np.random.randn(3,3)
print("Random Values from Normal Distribution")
print(random_normal)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Random Values between 0 and 1
[[0.53540156 0.83754366 0.53221386]
 [0.47800462 0.90325525 0.46851501]
 [0.22455981 0.0742872  0.98944124]]
Random Values from Normal Distribution
[[ 0.66880286 -1.14530728 -0.6132102 ]
 [ 0.48512882 -0.77634417  2.47846377]
 [-1.22804984 -1.44750407  0.06115387]]


In [22]:
#### Indexing Numpy Arrays ####

x = np.array([10,20,30,40,50])
print("Array:" , x)
print("Length of Array:" , len(x))

print("First Element", x[0])
print("Last Element", x[-1])
print("First 3 Elements", x[:3])
print("Last 3 Elements", x[2:])


Array: [10 20 30 40 50]
Length of Array: 5
First Element 10
Last Element 50
First 3 Elements [10 20 30]
Last 3 Elements [30 40 50]


In [31]:
### Indexing 2 Dimensional Arrays ###
matrix = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(matrix)
print(matrix.shape)

print("Element of Row 0 and Column 1" , matrix[0][1])
print("First Row" , matrix[0])
print("Second Column" , matrix[:,1])
print("Top left 2 x 2 Block" , matrix[:2,:2])
print("Top left 2 x 3 Block" , matrix[:2,:3])


[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
(3, 4)
Element of Row 0 and Column 1 20
First Row [10 20 30 40]
Second Column [ 20  60 100]
Top left 2 x 2 Block [[10 20]
 [50 60]]
Top left 2 x 3 Block [[10 20 30]
 [50 60 70]]


In [42]:
# Reshaping the Array
matrix = np.array([[1,2,3,4,5,6]])
print("Orginal" , matrix)
print("Shape" , matrix.shape)

matrix = matrix.reshape(3,2)
print("Reshaped" ,matrix)

matrix = np.array([[1, 2], [3, 4]])
flat = matrix.reshape(-1)
print("Flattened" , flat)

####Changing Index Order (C vs F)
### order='C' (Default): Fills the new array row-by-row.
### order='F': Fills the new array column-by-column

arr = np.array([1, 2, 3, 4, 5, 6])
col_major = arr.reshape((2, 3), order='F')
print("Fills the new array column-by-column")
print(col_major)

arr = np.array([1, 2, 3, 4, 5, 6])
row_major = arr.reshape((2, 3), order='C')
print("Fills the new array row-by-row")
print(row_major)



Orginal [[1 2 3 4 5 6]]
Shape (1, 6)
Reshaped [[1 2]
 [3 4]
 [5 6]]
Flattened [1 2 3 4]
Fills the new array column-by-column
[[1 3 5]
 [2 4 6]]
Fills the new array row-by-row
[[1 2 3]
 [4 5 6]]


In [47]:
### Element wise Operations
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

print("Addition\n" , a + b)
print("Subtraction\n" , a - b)
print("Multiplication \n" , a * b)
print("Division\n" , a / b)
print("Square\n" , a ** 2)

Addition
 [11 22 33 44]
Subtraction
 [ -9 -18 -27 -36]
Multiplication 
 [ 10  40  90 160]
Division
 [0.1 0.1 0.1 0.1]
Square
 [ 1  4  9 16]


In [50]:
#### Broadcasting ##########

x = np.array([1,2,3,4])
y = x + 10
print("Original" ,x)
print("After adding scalar" ,y)


Original [1 2 3 4]
After adding scalar [11 12 13 14]


In [53]:
### Broadcasting with 2 Dimensional Array ###

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix" , matrix)
print("Matrix Shape" , matrix.shape)

bias = np.array([10,20,30])
print("Bias" , bias)
print("Bias Shape" , bias.shape)
print("After Broadcasting" , matrix + bias)




Matrix [[1 2 3]
 [4 5 6]]
Matrix Shape (2, 3)
Bias [10 20 30]
Bias Shape (3,)
After Broadcasting [[11 22 33]
 [14 25 36]]


In [56]:
### Matrix Multiplication ####
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("Matrix A" , A)
print("Matrix B" , B)

print("Matrix Multiplication", A @ B)


Matrix A [[1 2]
 [3 4]]
Matrix B [[5 6]
 [7 8]]
Matrix Multiplication [[19 22]
 [43 50]]


In [60]:
## Manual Linear Layer ###
## y = xW + b

## Input 1 Sample with 3 features
x = np.array([1.0,2.0,3.0])
print(x)

## Weight Matrix : 3 input features with 2 output features
W = np.array([[0.1, 0.2],[0.3,0.4],[0.5,0.6]])
print(W)

# Bias
b = np.array([0.5,1.0])

y =x @ W + b

## Print Shapes
print("Input Shape" , x.shape)
print("Weight Shape", W.shape)
print("Bias Shape", b.shape)
print("Bias Shape", b.shape)
print("Output Shape" , y.shape)
print("Output" , y)


[1. 2. 3.]
[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]]
Input Shape (3,)
Weight Shape (3, 2)
Bias Shape (2,)
Bias Shape (2,)
Output Shape (2,)
Output [2.7 3.8]
