<a href="https://colab.research.google.com/github/karanamsubbarao/Python-Exercises/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
###Pytorch Bootcamp for Deep Learning

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

print("Pytorch version", torch.__version__)

Pytorch version 2.11.0+cpu


In [3]:
### Check GPU Availabilty
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)
if(torch.cuda.is_available()):
    print("GPU Name", torch.cuda.get_device_name(0))

cpu


In [4]:
### Creating Tensors

### Tensor from the list
x = torch.tensor([1,2,3,4])
print(x)

### Float Tensor
x = torch.tensor([1.0,2.0,3.0,4.0])
print(x)


### Matrix
matrix = torch.tensor([[1,2,3],[4,5,6]])
print(matrix)



tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
### Tensor Attributes
x = torch.randn(3,4)
print("Tensor",x)
print("Shape",x.shape)
print("Data Type",x.dtype)
print("Device",x.device)


Tensor tensor([[ 0.6470,  0.6011,  0.0607, -0.0510],
        [ 0.7802,  0.1472, -0.4858,  1.0172],
        [-1.6896, -0.7106, -0.6538,  0.7635]])
Shape torch.Size([3, 4])
Data Type torch.float32
Device cpu


In [6]:
###Special Tensor Creation
zeros = torch.zeros(3,4)
ones = torch.ones(2,5)
random_uniform = torch.rand(3,3)
random_normal = torch.randn(3,3)
identity = torch.eye(4)

print("Zeros",zeros)
print("Ones",ones)
print("Random Uniform",random_uniform)
print("Random Normal",random_normal)
print("Identity",identity)

Zeros tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Ones tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
Random Uniform tensor([[0.4630, 0.8525, 0.0442],
        [0.1599, 0.6124, 0.2618],
        [0.7607, 0.4082, 0.0360]])
Random Normal tensor([[-0.0141, -0.6470, -0.9320],
        [-0.1105, -1.2780,  2.1757],
        [-1.1555, -1.3299,  1.2839]])
Identity tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [7]:
### Tensor Indexing ####

x = torch.tensor([10,20,30,40,50])
print("X", x)
print("First Element", x[0])
print("Last Element", x[-1])
print("First 3 Elements", x[:3])
print("From Index 2 Onwards", x[2:])


X tensor([10, 20, 30, 40, 50])
First Element tensor(10)
Last Element tensor(50)
First 3 Elements tensor([10, 20, 30])
From Index 2 Onwards tensor([30, 40, 50])


In [8]:
# ============================================================
# 2D Tensor Indexing
# ============================================================

matrix = torch.tensor([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Matrix:")
print(matrix)

print("Element at row 0, column 1:", matrix[0, 1])
print("First row:", matrix[0])
print("Second column:", matrix[:, 1])
print("Top-left 2x2 block:")
print(matrix[:2, :2])


Matrix:
tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
Element at row 0, column 1: tensor(20)
First row: tensor([10, 20, 30])
Second column: tensor([20, 50, 80])
Top-left 2x2 block:
tensor([[10, 20],
        [40, 50]])


In [9]:
# ============================================================
# Tensor Reshaping
# ============================================================

x = torch.arange(12)

print("Original tensor:")
print(x)
print("Original shape:", x.shape)

x_reshaped = x.reshape(3, 4)

print("Reshaped tensor:")
print(x_reshaped)
print("Reshaped shape:", x_reshaped.shape)

Original tensor:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Original shape: torch.Size([12])
Reshaped tensor:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Reshaped shape: torch.Size([3, 4])


In [10]:
# ============================================================
# view() and reshape()
# Both are used to change tensor shape
# reshape() is generally safer
# ============================================================
x = torch.arange(12)
print("Before using view:")
print(x)

x_view = x.view(3, 4)
x_reshape = x.reshape(3, 4)

print("Using view:")
print(x_view)

print("Using reshape:")
print(x_reshape)

Before using view:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Using view:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Using reshape:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [11]:
# ============================================================
# unsqueeze() adds a dimension
# squeeze() removes dimensions of size 1
# ============================================================

x = torch.tensor([1, 2, 3, 4, 5, 6])

print("Original shape:", x.shape)

x_unsqueezed = x.unsqueeze(0)
print("After unsqueeze(0):", x_unsqueezed.shape)

x_unsqueezed_2 = x.unsqueeze(1)
print("After unsqueeze(1):", x_unsqueezed_2.shape)

x_squeezed = x_unsqueezed.squeeze()
print("After squeeze:", x_squeezed.shape)

Original shape: torch.Size([6])
After unsqueeze(0): torch.Size([1, 6])
After unsqueeze(1): torch.Size([6, 1])
After squeeze: torch.Size([6])


In [12]:
# ============================================================
# permute() changes the order of dimensions
# Important for images
# ============================================================

# Example image tensor: Height x Width x Channels
image_hwc = torch.randn(224, 224, 3)
print("Original image shape HWC:", image_hwc.shape)

# PyTorch CNNs expect: Channels x Height x Width
image_chw = image_hwc.permute(2, 0, 1)

print("After permute to CHW:", image_chw.shape)


Original image shape HWC: torch.Size([224, 224, 3])
After permute to CHW: torch.Size([3, 224, 224])


In [13]:
# ============================================================
# Basic Tensor Operations
# ============================================================
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([10.0, 20.0, 30.0])

print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)
print("a squared:", a ** 2)

a + b: tensor([11., 22., 33.])
a - b: tensor([ -9., -18., -27.])
a * b: tensor([10., 40., 90.])
a / b: tensor([0.1000, 0.1000, 0.1000])
a squared: tensor([1., 4., 9.])


In [14]:
# ============================================================
# Matrix Multiplication
# ============================================================
A = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0]
])

B = torch.tensor([
    [5.0, 6.0],
    [7.0, 8.0]
])

C = A @ B

print("A:")
print(A)

print("B:")
print(B)

print("A @ B:")
print(C)


A:
tensor([[1., 2.],
        [3., 4.]])
B:
tensor([[5., 6.],
        [7., 8.]])
A @ B:
tensor([[19., 22.],
        [43., 50.]])


In [15]:
# ============================================================
# Moving Tensor to GPU
# ============================================================

x = torch.randn(3, 4)
print("Before moving:", x.device)

x = x.to(device)
print("After moving:", x.device)

Before moving: cpu
After moving: cpu


In [16]:
# ============================================================
# Autograd
# PyTorch automatically calculates gradients
# ============================================================

x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3 * x + 1

print("y:", y)

# Compute dy/dx
y.backward()

print("Gradient dy/dx at x=2:", x.grad)

y: tensor(11., grad_fn=<AddBackward0>)
Gradient dy/dx at x=2: tensor(7.)


In [17]:
# ============================================================
# Autograd with Vectors
# ============================================================

x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

y = x ** 2

loss = y.mean()

print("y:", y)
print("loss:", loss)

loss.backward()

print("Gradient:", x.grad)

y: tensor([1., 4., 9.], grad_fn=<PowBackward0>)
loss: tensor(4.6667, grad_fn=<MeanBackward0>)
Gradient: tensor([0.6667, 1.3333, 2.0000])


In [18]:
# ============================================================
# Manual Linear Regression with Autograd
# y = wx + b
# ============================================================

x = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y_true = torch.tensor([[3.0], [5.0], [7.0], [9.0]])

w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
learning_rate = 0.01
for epoch in range(100):
    y_pred = x * w + b
    loss = torch.mean((y_pred - y_true) ** 2)
    loss.backward()
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

        w.grad.zero_()
        b.grad.zero_()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

print("Learned weight:", w.item())
print("Learned bias:", b.item())


Epoch 0, Loss: 10.1147
Epoch 10, Loss: 0.3239
Epoch 20, Loss: 0.0669
Epoch 30, Loss: 0.0569
Epoch 40, Loss: 0.0534
Epoch 50, Loss: 0.0503
Epoch 60, Loss: 0.0474
Epoch 70, Loss: 0.0446
Epoch 80, Loss: 0.0420
Epoch 90, Loss: 0.0396
Learned weight: 1.8393480777740479
Learned bias: 1.4723360538482666


In [19]:
# ============================================================
# nn.Module
# All PyTorch neural networks are written using nn.Module
# ============================================================

class LinearRegressionModel(nn.Module):

    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        output = self.linear(x)
        return output

model = LinearRegressionModel()

print(model)

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)


In [20]:
# ============================================================
# Training nn.Module Model
# ============================================================
x = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y_true = torch.tensor([[3.0], [5.0], [7.0], [9.0]])

model = LinearRegressionModel()

criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

for epoch in range(100):

    y_pred = model(x)

    loss = criterion(y_pred, y_true)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 0, Loss: 55.2858
Epoch 10, Loss: 1.6128
Epoch 20, Loss: 0.2136
Epoch 30, Loss: 0.1674
Epoch 40, Loss: 0.1568
Epoch 50, Loss: 0.1476
Epoch 60, Loss: 0.1390
Epoch 70, Loss: 0.1309
Epoch 80, Loss: 0.1233
Epoch 90, Loss: 0.1161


In [21]:
# ============================================================
# Inspect Model Parameters
# ============================================================

for name, parameter in model.named_parameters():
    print(name)
    print(parameter.data)

linear.weight
tensor([[2.2752]])
linear.bias
tensor([0.1908])


In [23]:
# ============================================================
# Linear Layer
# Input shape: batch_size x input_features
# Output shape: batch_size x output_features
# ============================================================
linear_layer = nn.Linear(in_features=4, out_features=3)
x = torch.randn(5, 4)
output = linear_layer(x)
print("Input shape:", x.shape)
print("Output shape:", output.shape)

Input shape: torch.Size([5, 4])
Output shape: torch.Size([5, 3])


In [24]:
# ============================================================
# Activation Functions
# ============================================================
x = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])
relu_output = F.relu(x)
sigmoid_output = torch.sigmoid(x)
tanh_output = torch.tanh(x)

print("Input:", x)
print("ReLU:", relu_output)
print("Sigmoid:", sigmoid_output)
print("Tanh:", tanh_output)

Input: tensor([-2., -1.,  0.,  1.,  2.])
ReLU: tensor([0., 0., 0., 1., 2.])
Sigmoid: tensor([0.1192, 0.2689, 0.5000, 0.7311, 0.8808])
Tanh: tensor([-0.9640, -0.7616,  0.0000,  0.7616,  0.9640])


In [25]:
# ============================================================
# Softmax
# Converts logits into probabilities
# ============================================================

logits = torch.tensor([[2.0, 1.0, 0.1]])

probabilities = F.softmax(logits, dim=1)

print("Logits:", logits)
print("Probabilities:", probabilities)
print("Sum:", probabilities.sum())

Logits: tensor([[2.0000, 1.0000, 0.1000]])
Probabilities: tensor([[0.6590, 0.2424, 0.0986]])
Sum: tensor(1.0000)


In [26]:
# ============================================================
# CrossEntropyLoss
# Important:
# It expects raw logits, not softmax probabilities
# ============================================================

logits = torch.tensor([
    [2.0, 1.0, 0.1],
    [0.5, 2.5, 0.3]
])

targets = torch.tensor([0, 1])

criterion = nn.CrossEntropyLoss()

loss = criterion(logits, targets)

print("Loss:", loss.item())

Loss: 0.31853973865509033


In [27]:

# ============================================================
# Custom Dataset
# ============================================================
from torch.utils.data import Dataset, DataLoader
class SimpleDataset(Dataset):

    def __init__(self):
        self.X = torch.randn(100, 2)
        self.y = (self.X[:, 0] + self.X[:, 1] > 0).long()

    def __len__(self):
        return len(self.X)

    def __getitem__(self, index):
        return self.X[index], self.y[index]

dataset = SimpleDataset()

print("Number of samples:", len(dataset))

sample_x, sample_y = dataset[0]

print("Sample input:", sample_x)
print("Sample label:", sample_y)

Number of samples: 100
Sample input: tensor([1.7513e+00, 1.0920e-03])
Sample label: tensor(1)


In [28]:
# ============================================================
# DataLoader
# ============================================================

dataloader = DataLoader(
    dataset,
    batch_size=16,
    shuffle=True
)

for batch_x, batch_y in dataloader:
    print("Batch input shape:", batch_x.shape)
    print("Batch label shape:", batch_y.shape)
    break

Batch input shape: torch.Size([16, 2])
Batch label shape: torch.Size([16])


In [29]:
# ============================================================
# MLP for Binary Classification
# ============================================================

class MLP(nn.Module):

    def __init__(self, input_dim, hidden_dim, num_classes):
        super().__init__()

        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, num_classes)

    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)

        x = self.fc2(x)
        x = F.relu(x)

        x = self.fc3(x)

        return x

model = MLP(input_dim=2, hidden_dim=32, num_classes=2).to(device)

print(model)

MLP(
  (fc1): Linear(in_features=2, out_features=32, bias=True)
  (fc2): Linear(in_features=32, out_features=32, bias=True)
  (fc3): Linear(in_features=32, out_features=2, bias=True)
)


In [30]:
# ============================================================
# Training MLP
# ============================================================

dataset = SimpleDataset()

dataloader = DataLoader(
    dataset,
    batch_size=16,
    shuffle=True
)

model = MLP(input_dim=2, hidden_dim=32, num_classes=2).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 20

for epoch in range(epochs):

    model.train()

    total_loss = 0
    correct = 0
    total = 0

    for batch_x, batch_y in dataloader:

        batch_x = batch_x.to(device)
        batch_y = batch_y.to(device)

        logits = model(batch_x)

        loss = criterion(logits, batch_y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        predictions = torch.argmax(logits, dim=1)
        correct += (predictions == batch_y).sum().item()
        total += batch_y.size(0)

    accuracy = correct / total

    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}, Accuracy: {accuracy:.4f}")

Epoch 1, Loss: 4.8077, Accuracy: 0.5200
Epoch 2, Loss: 4.5913, Accuracy: 0.7400
Epoch 3, Loss: 4.3807, Accuracy: 0.8800
Epoch 4, Loss: 4.1263, Accuracy: 0.9000
Epoch 5, Loss: 3.9815, Accuracy: 0.9000
Epoch 6, Loss: 3.6578, Accuracy: 0.9000
Epoch 7, Loss: 3.4836, Accuracy: 0.9100
Epoch 8, Loss: 3.2488, Accuracy: 0.9100
Epoch 9, Loss: 3.1380, Accuracy: 0.9100
Epoch 10, Loss: 2.8318, Accuracy: 0.9300
Epoch 11, Loss: 2.5031, Accuracy: 0.9300
Epoch 12, Loss: 2.2607, Accuracy: 0.9400
Epoch 13, Loss: 2.0675, Accuracy: 0.9400
Epoch 14, Loss: 1.9066, Accuracy: 0.9400
Epoch 15, Loss: 1.6614, Accuracy: 0.9400
Epoch 16, Loss: 1.4729, Accuracy: 0.9500
Epoch 17, Loss: 1.4056, Accuracy: 0.9600
Epoch 18, Loss: 1.2017, Accuracy: 0.9600
Epoch 19, Loss: 1.0780, Accuracy: 0.9700
Epoch 20, Loss: 1.0700, Accuracy: 0.9700
